---
title: "EDA & Additive Model"
author: "Xiaowei Zeng"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(survival)
library(survminer)
library(ggplot2)
library(glmnet)
library(sqldf)
library(MASS)
library(EnvStats)

#check distribution
distribution_plot <- function(df, x) {
  par(mfrow = c(2,2))
  #histogram
  hist(df[[x]], main = paste("Histogram of", x))
  #qq plot
  qqnorm(df[[x]], main = paste("Custom QQ Plot Title: ", x))
  qqline(df[[x]])
}

```

```{r}
source("data_loading.R")
```

```{r}
library(gtsummary)
sum_table = tbl_summary(data[-c(1:3)], by = "wghist")
```

```{r}
library(flextable)
mytable = as_flex_table(sum_table)
save_as_docx(mytable, path = "mytable.docx")
```

```{r}
surv = Surv(data$event, data$status)
```

## KM Estimators

```{r}
plot_KM = function(KM_curve, title, conf.int = T, legend = c(0.2, 0.2)){
  ggsurvplot(KM_curve,
           data=data,
           conf.int = conf.int,
           palette="jama",
           ggtheme=theme_bw(),
           # xlim=c(0, 52),
           ylab="Survival Probability",
           ylim=c(0.8, 1.01),
           axes.offset=F,
           legend = legend,
           legend.title = title)
}
```


### Low hourly wage history 
```{r}
p1 = plot_KM(survfit(surv~wghist, data=data), "Low Wage History", legend = c(0.2, 0.25))$plot
survdiff(surv~wghist, data=data)
```

### Employment Stability
```{r}
p2 = plot_KM(survfit(surv ~ employ, data=data), "Employment Stability")$plot
survdiff(surv ~ employ, data=data)
```

### Race
```{r}
p3 = plot_KM(survfit(surv ~ race, data=data), "Race",
        conf.int = F, legend = c(0.18, 0.3))$plot
survdiff(surv ~ race, data=data)
```

### Gender
```{r}
p4 = plot_KM(survfit(surv ~ gender, data=data), "Gender")$plot
survdiff(surv ~ gender, data=data)
```

### Personal Education
```{r}
p5 = plot_KM(survfit(surv ~ edu, data=data), "Personal Education")$plot
survdiff(surv ~ edu, data=data)
```

### Parental Education
```{r}
p6 = plot_KM(survfit(surv ~ pedu, data=data), "Parental Education")$plot
survdiff(surv ~ pedu, data=data)
```

### Religion
```{r}
p7 = plot_KM(survfit(surv ~ religion, data=data), "Religion",
        conf.int = F, legend = c(0.2, 0.4))$plot
survdiff(surv ~ religion, data=data)
```

### Living Areas
```{r}
p8 = plot_KM(survfit(surv ~ live, data=data), "Living Areas",
        conf.int = F, legend = c(0.2, 0.4))$plot
survdiff(surv ~ live, data=data)
```

### Marriage
```{r}
p9 = plot_KM(survfit(surv ~ marriage, data=data), "Marriage")$plot
survdiff(surv ~ marriage, data=data)
```

### Covered by Government Insurance
```{r}
p10 = plot_KM(survfit(surv ~ insur_gov, data=data), "Government Insurance",
        conf.int = F, legend = c(0.23, 0.25))$plot + labs(subtitle = "KM curve for insur_gov")
survdiff(surv ~ insur_gov, data=data)
```

### Covered by Employer's Insurance
```{r}
p11 = plot_KM(survfit(surv ~ insur_com, data=data), "Employer's Insurance")$plot
survdiff(surv ~ insur_com, data=data)
```

### Self-Reported Health
```{r}
p12 = plot_KM(survfit(surv ~ self_health, data=data), "Self-Reported Health", legend = c(0.35, 0.2))$plot
survdiff(surv ~ self_health, data=data)
```

### Ever Smoke
```{r}
p13 = plot_KM(survfit(surv ~ smoke, data=data), "Smoke")$plot
survdiff(surv ~ smoke, data=data)
```

```{r}
library(patchwork)
p = p1 + p2 + p3 + p5 + p6 + p13 + p4 + p9 + p12

ggsave("p1.png", p, width = 14, height = 9)
```


## Cox Model

```{r}
lasso_cox <- coxph(surv_object ~ wghist + age + race + pedu + insur_gov + self_health + smoke, data = data)
AIC(lasso_cox)
summary(lasso_cox)
```

## Additive Model

```{r}
library(scales)
library(ggsci)
mypalette = c(pal_jama("default")(7), 
              "#003C67", "#7C878E", "#363062", "#F1B4BB", "#662549")
show_col(mypalette)
```


```{r}
library(timereg)
source("geom_stepribbon.R")

coef_aalen <- function(aa, level=0.05){
  list(time=aa[["cum"]][, 1],
       yy=aa[["cum"]][, -1],
       ylow=aa[["cum"]][,-1]-qnorm(1-level/2)*sqrt(aa[["var.cum"]][,-1]),
       yup=aa[["cum"]][,-1]+qnorm(1-level/2)*sqrt(aa[["var.cum"]][,-1]))
}
```


```{r}
aa1 = aalen(surv ~ wghist + age + race + pedu + insur_gov + self_health + smoke, data = data, n.sim = 300, start.time = 0)
summary(aa1)
coefs <- coef_aalen(aa1)
plots <- lapply(1:ncol(coefs$yy), function(i) {
  ggplot() + geom_step(mapping=aes(x=coefs$time, y=coefs$yy[, i]),
                     color=mypalette[i], size=0.8) +
  geom_stepribbon(mapping=aes(x=coefs$time,
                              ymin=coefs$ylow[, i],
                              ymax=coefs$yup[, i]),
                  alpha=0.32,
                  fill=mypalette[i]) +
  theme_bw() + theme(plot.subtitle = element_text(hjust = 0.5)) +
  labs(x=element_blank(), y=element_blank(),
       subtitle=colnames(coefs$yy)[i])}) %>% do.call(grid.arrange, .)
```

```{r}
library(gridExtra)

aa2 = aalen(surv ~ wghist + age + const(race) + const(pedu) + insur_gov +
              const(self_health) + smoke, data=data, n.sim=300, start.time=0)
summary(aa2)
coefs <- coef_aalen(aa2)
plots <- lapply(1:ncol(coefs$yy), function(i) {
  ggplot() + geom_step(mapping=aes(x=coefs$time, y=coefs$yy[, i]),
                     color=mypalette[i], linewidth=0.8) +
  geom_stepribbon(mapping=aes(x=coefs$time,
                              ymin=coefs$ylow[, i],
                              ymax=coefs$yup[, i]),
                  alpha=0.32,
                  fill=mypalette[i]) +
  theme_bw() + theme(plot.subtitle = element_text(hjust = 0.5)) +
  labs(x=element_blank(), y=element_blank(),
       subtitle=colnames(coefs$yy)[i])})
p = plots[[2]] + plots[[3]] + plots[[4]] + plots[[5]] + plots[[6]] + plots[[7]]
ggsave("aa.png", p, width = 14, height = 9)
```

```{r}
aa3 = aalen(surv ~ const(wghist) + age + const(race) + const(pedu) + insur_gov + const(self_health) + smoke, data=data, n.sim=300, start.time=0)
summary(aa3)
coefs <- coef_aalen(aa3)
plots <- lapply(1:ncol(coefs$yy), function(i) {
  ggplot() + geom_step(mapping=aes(x=coefs$time, y=coefs$yy[, i]),
                     color=mypalette[i], size=0.8) +
  geom_stepribbon(mapping=aes(x=coefs$time,
                              ymin=coefs$ylow[, i],
                              ymax=coefs$yup[, i]),
                  alpha=0.32,
                  fill=mypalette[i]) +
  theme_bw() + theme(plot.subtitle = element_text(hjust = 0.5)) +
  labs(x=element_blank(), y=element_blank(),
       subtitle=colnames(coefs$yy)[i])}) %>% do.call(grid.arrange, .)
```





